server:
  port: 8099
spring:
  datasource:
    url: jdbc:mysql://10.222.29.209:3306/parking_reservation_service?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT&useAffectedRows=true
    username: root
    password: 83aeb88a
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 5000MB
mybatis:
  mapperLocations: classpath:/mapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: false #pageSize=0
